version: "3.3"
services:
  test_db:
    image: comments_db
    restart: always
    env_file: .env
    volumes:
      - ./test_pg_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  test_backend:
    image: comments_backend_test
    restart: always
    env_file: .env
    environment:
      - DATABASE_HOST=test_db
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/backend
    depends_on:
      - test_db