"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import json
from pathlib import Path

from django.utils.translation import gettext_lazy as _

from settings.auth import *  # noqa: F405, F403
from settings.cache import *  # noqa: F405, F403
from settings.celery import *  # noqa: F405, F403
from settings.channels import *  # noqa: F405, F403
from settings.drf import *  # noqa: F405, F403
from settings.emails import *  # noqa: F405, F403

DEBUG: bool = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent  # backend   # noqa: F405
STATIC_ROOT: Path = BASE_DIR / 'staticfiles'  # noqa: F405
MEDIA_ROOT: Path = BASE_DIR / 'media'  # noqa: F405

SERVER_URL: str = os.environ.get('SERVER_URL', 'http://localhost:8000')  # noqa: F405

STATICFILES_DIRS: tuple = (
    BASE_DIR / 'admin/static',
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = os.environ.get('DJANGO_SECRET_KEY')  # noqa: F405

# SECURITY WARNING: don't run with debug turned on in production!
SITE_ID = 1

ALLOWED_HOSTS: tuple = ('*',)

# Application definition

INSTALLED_APPS: list = [
    'admin.CommentsAdminSiteAdminConfig',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',  # swagger and redoc docs

    'apps.comments.apps.CommentsAppConfig',
    'apps.user.apps.UserAppConfig',
]


MIDDLEWARE: list = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF: str = 'api.urls'

TEMPLATES: list = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'admin/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'comments'),
        'USER': os.environ.get('POSTGRES_USER', 'comments_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        "HOST": os.environ.get('DATABASE_HOST', 'db'),
        "PORT": int(os.environ.get('DATABASE_PORT', 5432)),

    }
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n /

LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),)
LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
]

USE_I18N = True
USE_L10N = True

USE_TZ = True
TIME_ZONE = 'Europe/Kiev'

TIME_FORMAT = 'YYYY-MM-DD hh:mm:ss'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

